# See default settings https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
AllCops:
  TargetRubyVersion: ~
  Exclude:
    - '**/*.jbuilder'
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '**/Gemfile'
    - '**/Brewfile'
    - '**/Capfile'
    - '**/Guardfile'

Metrics/AbcSize:
  Max: 29

# Avoid classes longer than 300 lines of code.
Metrics/ClassLength:
  Enabled: true
  Max: 300

# Limit lines to 120 characters.
Layout/LineLength:
  Enabled: true
  Max: 150

# Avoid methods longer than 55 lines of code
Metrics/MethodLength:
  Enabled: true
  Max: 55

Metrics/BlockNesting:
  Max: 4
# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolProc:
  Enabled: false

# Add underscores to large numeric literals to improve their readability.
Style/NumericLiterals:
  Enabled: false

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false

# Align the elements of a hash literal if they span more than one line.
Layout/HashAlignment:
  Enabled: false

# Align the parameters of a method call if they span more than one line.
Layout/ParameterAlignment:
  Enabled: false

# Favor modifier if/unless usage when you have a single-line body.
Style/IfUnlessModifier:
  Enabled: false

# Use the new lambda literal syntax for single-line blocks.
Style/Lambda:
  Enabled: false

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

Style/SignalException:
  # Valid values are: semantic, only_raise and only_fail
  EnforcedStyle: only_raise

# Don't use assignment in conditions.
Lint/AssignmentInCondition:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$redis]

Naming/PredicateName:
  Enabled: false

Naming/FileName:
  Exclude:
    # Convention with other omniauth-* libraries.
    - 'lib/omniauth-pixiv.rb'
    - 'app/views/admin/provider_orders/index.xlsx+teis-p.axlsx'
    - 'lib/tasks/i18n-js.rake'

Lint/RescueException:
  Exclude:
    # To log all exceptions.
    - 'lib/server_error_logging.rb'
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

# バグがある。concerning block内にあるprivateを誤検知する
Lint/UselessAccessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()

# is_expected.to change { hoge } が引っかかる…
Lint/AmbiguousBlockAssociation:
  Enabled: false

# `alias_method` is prefered to `alias`
Style/Alias:
  Enabled: false

# set prefix is allowed
Naming/AccessorMethodName:
  Enabled: false

# Use a consistent style for named format string tokens.
Style/FormatStringToken:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
