version: "3"
services:
  doc:
    image: swaggerapi/swagger-ui:latest
    container_name: doc
    volumes:
      - ./etc/docs/swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/scheme/reference/rooms.v1.yaml
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.6
    volumes:
      - ./.docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    command: "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - /myapp/vendor
      - /myapp/log
      - /myapp/.git
      - tmp-data:/myapp/tmp
    environment:
      database_user: "root"
      database_pass: "password"
      database_host: mysql
      redis_url: redis://redis:6379
    depends_on:
      - mysql
      - redis

  # for-test
  nginx:
    image: nginx:1.10.3
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  bundle:
    driver: local
